name-template: 'backend_v$RESOLVED_VERSION 🌈'
tag-template: 'backend_v$RESOLVED_VERSION'

filter-by-commitish: true
commitish: backend-release

categories:
  - title: Backend New Features 🛠
    label: 'backend'
  - title: ${{ vars.COMMON_LIBRARY_TITLE }}
    labels:
      - 'common-library'
      - 'doc'
  - title: CI/CD changes ♾️
    label: 'ci'
  - title: Infrastructure changes 🏗️
    label: 'infra'

version-resolver:
  major:
    labels:
      - 'back-breaking-changes'
  minor:
    labels:
      - 'back-minor-changes'
  default: patch

include-labels:
  - 'backend'
  - 'common-library'
  - 'ci'
  - 'infra'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

header: |
  ## What's Changed

template: |
  $CHANGES
