name: pr_create_ephemeral_environment

on:
  pull_request:
    types: [opened, synchronize, labeled]

  trigger-ephemeral-backend:
    if: contains(github.event.pull_request.labels.*.name, 'backend')
    runs-on: ubuntu-latest
    steps:
      - name: Bypass backend deployment
        if: contains(github.event.pull_request.labels.*.name, 'no-infra') || !contains(github.event.pull_request.labels.*.name, 'backend')
        run: exit 1
      - name: CircleCI ephemeral backend deployment
        if: !contains(github.event.pull_request.labels.*.name, 'no-infra')
        id: ephemeral_backend_created
        run: echo "Deployed"