name: pr_create_ephemeral_environment

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  trigger-ephemeral-environment:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI ephemeral backend deployment
        id: ephemeral_backend_created
        env:
          VARIABLE: '${{ github.event.pull_request.labels.*.name }}'
        run: echo $VARIABLE