name: backend_release_published_deploy_live_environment

on:
  release:
    types: [published]

jobs:
  trigger-live-backend-deploy:
    if: contains(github.ref, 'backend_v')
    runs-on: ubuntu-latest
    steps:
      - run: echo "lala"
