name: pr_create_ephemeral_environment

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  trigger-ephemeral-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Get Labels
        id: get_labels
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/labels

      - name: Store Labels in Variable
        run: echo "LABELS=${{ steps.get_labels.outputs.data }}" >> $GITHUB_ENV
