name: frontend_release_published_deploy_live_environment

on:
  release:
    types: [published]

jobs:
  trigger-live-frontend-deploy:
    if: contains(github.ref, 'frontend_v')
    runs-on: ubuntu-latest
    steps:
      - run: echo "lala"
