name: pr_destroy_ephemeral_environment
on:
  pull_request:
    types: [closed]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - run: |
          env
      #            - name: CircleCI Trigger on Closed Pull Request
      #              id: ephemeral_environment_destroy
      #              uses: axel-springer-kugawana/trigger-circleci-pipeline-action@v1.0.6
      #              env:
      #                  CCI_TOKEN: ${{ secrets.CCI_TOKEN }}