name: import-gpg

on:
  push:
    branches: main

jobs:
  sign-commit:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      -
        name: Sign commit and push changes
        run: |
          git checkout -b test_verified
      - name: add push
        run: |
          export GPG_TTY=$(tty)
          echo foodididididi > bar.txt
          git add .
          git commit -m "This commit is signed!"
          git push origin test_verified