name: Destroy ephemeral

on:
  delete:
    branches: # we focus on the branches deletion in order to not handle deleted tags hi hi
      - "**"

jobs:
  trigger-circleci:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Get PR number
        id: get_pr_number
        run: |
          BRANCH_NAME="${{ github.event.ref#refs/heads/ }}"
          PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')
          echo $PR_NUMBER
          echo "::set-output name=pr_number::$PR_NUMBER"
      - name: CircleCI Trigger on delete branches and tags
        run: echo tada !
