name: import-gpg

on:
  push:
    branches: main
# oui

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.BOT_GITHUB_TOKEN1 }}
#          ref: test_verified
      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: 12344566
          passphrase: toto
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Change some files
        run: |
          echo 'adding a new commit now' >> README.md
          git commit -m "this is bot" README.md
          git push origin test_verified
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}

