name: Destroy ephemeral

on:
  delete

jobs:
  trigger-circleci:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get PR number
        id: get_pr_number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --state closed --head ${{ github.event.ref }} --json number --jq '.[0].number')
          echo $PR_NUMBER
          echo "{pr_number}={$PR_NUMBER}" >> $GITHUB_OUTPUT

      - name: CircleCI Trigger on delete branches and tags
        run: echo ${{ steps.get_pr_number.outputs.pr_number }}