name: 'Get release note'

on:
  release:
    types: [published]

jobs:
  release_backend_note:
    if: contains(github.event.release.body, 'Common library changes 🎊') && contains(github.ref, 'frontend_v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Action
        uses: actions/checkout@v2
      - name: 'git get release'
        id: get_draft_release_note_id
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
        with:
          draft: true
          releaseNameRegEx: /backend_v[0-9]+\.[0-9]+\.[0-9]+.*/
      - name: Publish release
        uses: StuYarrow/publish-release@v1.1.2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            id: ${{ steps.get_draft_release_note_id.outputs.id }}

  release_frontend_note:
    if: contains(github.event.release.body, 'Common library changes 🎊') && contains(github.ref, 'backend_v')
    runs-on: ubuntu-latest
    steps:
      - name: 'git get release'
        id: get_git_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          releaseNameRegEx: /frontend_v[0-9]+\.[0-9]+\.[0-9]+.*/
