name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # This is important if you have branch protection rules!
      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6.1
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Change some files
        run: git checkout -b test && echo 'adding a new commit now' >> README.md
      - name: Commit changes to README.md file
        run: git commit -S -m "this is bot" README.md
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
            GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
            GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
            GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      - name: Git push
        run: git push origin test