name: 'Get release note'

on:
  release:
    types: [published]

jobs:
  release_backend_note:
    if: contains(github.event.release.body, 'Common library changes 🎊') && contains(github.ref, 'frontend_v')
    runs-on: ubuntu-latest
    steps:
      - name: 'git get release'
        id: get_git_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          releaseNameRegEx: /frontend_v[0-9]+\.[0-9]+\.[0-9]+/

  release_frontend_note:
    if: contains(github.event.release.body, 'Common library changes 🎊') && contains(github.ref, 'backend_v')
    runs-on: ubuntu-latest
    steps:
      - name: 'git get release'
        id: get_git_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          releaseNameRegEx: /backend_v[0-9]+\.[0-9]+\.[0-9]+/
